version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=welcome@123
      - MYSQL_DATABASE=srinidhi
      - MYSQL_USER=sri
      - MYSQL_PASSWORD=welcome@123
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    networks:
      - mynet
  web:
    image: apache-php-mysql:1
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.labels.node == manager
    ports:
      - 9999:80
    depends_on:
      - db
    networks:
      - mynet
networks:
  mynet:
